{{- if not .Values.cluster.kubeovn }}
kind: Service
apiVersion: v1
metadata:
  name: ovn-nb
  namespace: nauti-system
spec:
  clusterIP:
  {{- range (lookup "v1" "Service" "kube-system" "").items }}
  {{- if eq (dig "k8s-app" "no-kube-dns" .metadata.labels) "kube-dns" }}
  {{- $last_part := splitList "." (.spec.clusterIP | trimAll "\n") | last | add 2 }}
     {{ concat (slice (splitList "." .spec.clusterIP) 0 3 ) (list $last_part) | join "."}}
  {{- end }}
  {{- end }}
  ports:
    - name: ovn-nb
      protocol: TCP
      port: 6641
      targetPort: 6641
  type: ClusterIP
  selector:
    app: ovn-central
    ovn-nb-leader: "true"
  sessionAffinity: None
  {{- end }}