{{- if not .Values.cluster.kubeovn }}
kind: Service
apiVersion: v1
metadata:
  name: ovn-northd
  namespace: nauti-system
spec:
  ports:
    - name: ovn-northd
      protocol: TCP
      port: 6643
      targetPort: 6643
  type: ClusterIP
  selector:
    app: ovn-central
    ovn-northd-leader: "true"
  sessionAffinity: None
{{- end }}